### ISSUE TITLE
guzzlehttp/guzzle 7.0

### ISSUE THREAD

**Issue by moell-peng** [iMactool/jinritemai#16]
👍 ,非常棒的项目，能否兼容下  guzzle v7 版本 , 依赖变更为 `"guzzlehttp/guzzle": "^6.5|^7.0.1"`  。

**Comment by iMactool** [comment]
谢谢。晚点我来加上

**Comment by iMactool** [comment]
更新到最新的 `v1.2.1` 版本，再试试。
